### ISSUE TITLE
Load fonts

### ISSUE THREAD

**Issue by csbatista** [cburgmer/rasterizeHTML.js#129] opened 2016-02-25 14:36 UTC
How can I load fonts that are in an external file? 
The files are in the same cakePHP project, so I don't think that the problem is about cross origin.
I'm appending a string containing the css rules to the begining of the HTML string that I send for rasterizeHML. I tried putting the font-face rule at the begining of the string but it doesn't seem to work. How is the best way to do this? What can I be doing wrong? It is possible that being in a local server (Wamp) is the problem?

Here is an example of my code:

```
html = $("#exportar_container").html().trim();
html = "<style>@font-face { font-family: 'DIN'; src: url('/website/fonts/DIN/DINBold.ttf'); src: url('/website/fonts/DIN/DINBold.woff') format('woff'), url('/website/fonts/DIN/DINBold.svg') format('svg'), url('/website/fonts/DIN/DINBold.ttf') format('truetype');} #exportar { font-family: 'DIN';} </style>" + html;

rasterizeHTML.drawHTML(html, canvas);
```

Thank you for any ideas or suggestions!

**Comment by cburgmer** [comment] 2016-02-25 15:11
In the background rasterizehtml will load all assets, so the browser's dev tools should at least indicate the font being loaded (via XHR). Alternatively you can use the [`errors` field in the return value](https://github.com/cburgmer/rasterizeHTML.js/wiki/API#return-value) to programmatically find load issues.

Also, you might be successful in setting up an example on jsfiddle or alternatives. I could then have a look. Google fonts [support CORS](https://developers.google.com/fonts/docs/troubleshooting#CORS_header) to work around the same origin issue, and https://www.brcdn.org/?module=rasterizehtml&version=1.2.2 can offer you a hosted version of rasterizehtml.

Also, when in doubt maybe try both Firefox and Chrome.

**Comment by csbatista** [comment] 2016-02-26 11:42
Thank you for your quick reply! I did what you suggested and the font is indeed being loaded. I will try to work from this point now, and if I find out something I let you know.
Thank you!

**Comment by cburgmer** [comment] 2016-02-26 12:32
What might help you with debugging is to use the resulting SVG that is returned alongside the list of errors. This is technically the final output of rasterizehtml which is then rendered into the canvas by the browser. With the SVG's source code you should be able to debug in a straightforward fashion without depending on rasterizehtml itself.

**Comment by csbatista** [comment] 2016-02-26 13:33
On the svg element, the font-face rule appears empty. On the string that I pass to rasterizeHTML, it is in the following format:

```
@font-face { 
   font-family: DIN, 
   src: url(http://localhost:8888/website/fonts/DIN/DINBold.woff) 
} 
```

The page that I'm on is http://localhost:8888/website/some_url

What can be causing this? The protocol? The local environment? Something else?

Thank you for the support.

**Comment by cburgmer** [comment] 2016-02-26 15:02
Can you confirm that this is not the issue fixed in https://github.com/cburgmer/rasterizeHTML.js/releases/tag/1.2.2 (downstream https://github.com/cburgmer/inlineresources/releases/tag/0.1.7) where in Chrome font-face `url()` would be generated empty, missing the URL? Firefox is not affected, so that's a way of cross checking.

**Comment by csbatista** [comment] 2016-02-29 12:05
@cburgmer I don't think so. In my case, the whole font-face is empty, not only the url field. The begining of my svg is:

`<svg xmlns="http://www.w3.org/2000/svg" width="493" height="254" font-size="16px"><foreignObject x="0" y="0" width="489" height="250" style="float: left;" externalResourcesRequired="true"><html xmlns="http://www.w3.org/1999/xhtml"><head><style>@font-face { }  ` [...]

The same happens in Firefox.
I let you know if I find out something new.

**Comment by cburgmer** [comment] 2016-03-01 13:16
Thanks for checking. 

Your most recent example does not match the one from your initial ticket. It looks like invalid. I am assuming a typo when posting, but please verify.

Here's your latest `@font-face` example parsed and serialised back: http://jsfiddle.net/cburgmer/tk4kxLso/. All this code does is exercise the default CSSOM API of the browser, the one rasterizehtml should also be using (with the exception currently of Chrome where we provide a shim). It parses and serialises back the CSS rules. This might help you debugging. If your code passes through just fine, then I would assume the error is further down the line.

If you want to dig into the code, then https://github.com/cburgmer/inlineresources/blob/master/src/inlineCss.js#L100 and https://github.com/cburgmer/inlineresources/blob/master/src/cssSupport.js#L71 might be worth a look, this is where the grunt work happens.

**Comment by cburgmer** [comment] 2016-10-31 14:27
I'll assume the issue is solved. Closing for now, but feel free to re-open.

**Closed by cburgmer** 2016-10-31 14:27 UTC
